// Package fractal implements Fractal Neural Networks.
//
// REVOLUTIONARY IDEA: Weights are generated by a fractal formula.
//
// Like the Mandelbrot set (infinite complexity from z²+c),
// a fractal neural network generates unlimited weights from a tiny formula.
//
// The formula has SELF-SIMILARITY: weights at different layers
// follow the same pattern at different scales. This creates a
// natural inductive bias toward hierarchical representations.
//
// 8 parameters → unlimited weights → unlimited network depth
package fractal

import (
	"fmt"
	"math"
	"time"
)

// FractalNet is a neural network whose weights are computed by a fractal formula.
type FractalNet struct {
	// The fractal formula: W(i,j,depth) = f(a,b,c,d, i/N, j/M, depth)
	// Only 8 parameters define the ENTIRE network
	A, B, C, D     float32 // Fractal parameters
	E, F, G, H     float32 // Additional parameters for variety
	Depth          int     // Number of layers
	InputDim       int
	OutputDim      int
	HiddenDim      int
}

// New creates a fractal network with random initial parameters.
func New(inputDim, hiddenDim, outputDim, depth int) *FractalNet {
	return &FractalNet{
		A: randn() * 0.5,
		B: randn() * 0.5,
		C: randn() * 0.5,
		D: randn() * 0.5,
		E: randn() * 0.5,
		F: randn() * 0.5,
		G: randn() * 0.5,
		H: randn() * 0.5,
		Depth:     depth,
		InputDim:  inputDim,
		OutputDim: outputDim,
		HiddenDim: hiddenDim,
	}
}

// Weight computes a single weight using the fractal formula.
// This is the CORE INNOVATION: weights are computed, not stored.
//
// The formula combines:
// 1. Sinusoidal patterns (like Fourier features)
// 2. Recursive self-similarity (like fractals)
// 3. Position-dependent variation (like coordinate networks)
func (f *FractalNet) Weight(row, col, layer, inDim, outDim int) float32 {
	// Normalize positions to [0, 1]
	r := float32(row) / float32(max(inDim, 1))
	c := float32(col) / float32(max(outDim, 1))
	l := float32(layer) / float32(max(f.Depth, 1))

	// Fractal formula: combination of sinusoidal waves at different frequencies
	// This creates self-similar patterns at different scales
	w := f.A*sin(f.B*r+f.C*c) + f.D*cos(f.E*l+f.F*r)
	w += f.G*sin(f.H*c*l) * cos(f.A*r+f.D*l)

	// Add recursive self-similarity: deeper layers use finer-scale patterns
	scale := float32(math.Pow(2, float64(layer)))
	w += f.B * sin(r*scale) * cos(c*scale) * 0.1

	// Normalize to reasonable range
	return w * 0.3
}

// Bias computes a bias value using the fractal formula.
func (f *FractalNet) Bias(idx, layer, dim int) float32 {
	x := float32(idx) / float32(max(dim, 1))
	l := float32(layer) / float32(max(f.Depth, 1))
	return (f.C*sin(f.D*x+f.E*l) + f.G*cos(f.H*x)) * 0.1
}

// Forward computes the output by generating all weights on-the-fly.
func (f *FractalNet) Forward(input []float32) []float32 {
	x := input

	dims := f.layerDims()
	for layer := 0; layer < len(dims)-1; layer++ {
		inDim := dims[layer]
		outDim := dims[layer+1]

		output := make([]float32, outDim)
		for j := 0; j < outDim; j++ {
			sum := f.Bias(j, layer, outDim)
			for i := 0; i < inDim; i++ {
				w := f.Weight(i, j, layer, inDim, outDim)
				sum += x[i] * w
			}
			// ReLU for hidden layers, linear for output
			if layer < len(dims)-2 {
				sum = relu(sum)
			}
			output[j] = sum
		}
		x = output
	}
	return x
}

func (f *FractalNet) layerDims() []int {
	dims := []int{f.InputDim}
	for i := 0; i < f.Depth; i++ {
		dims = append(dims, f.HiddenDim)
	}
	dims = append(dims, f.OutputDim)
	return dims
}

// ParamCount returns stored parameters (always 8).
func (f *FractalNet) ParamCount() int { return 8 }

// VirtualParamCount returns the number of weights computed on-the-fly.
func (f *FractalNet) VirtualParamCount() int {
	count := 0
	dims := f.layerDims()
	for i := 0; i < len(dims)-1; i++ {
		count += dims[i]*dims[i+1] + dims[i+1] // weights + biases
	}
	return count
}

// Train optimizes the 8 fractal parameters using evolutionary strategy.
func (f *FractalNet) Train(inputs [][]float32, targets [][]float32, epochs, population int) {
	fmt.Printf("🌀 Fractal Neural Network Training\n")
	fmt.Printf("   Stored params: %d\n", f.ParamCount())
	fmt.Printf("   Virtual params: %d\n", f.VirtualParamCount())
	fmt.Printf("   Compression: %.0fx\n", float64(f.VirtualParamCount())/float64(f.ParamCount()))
	fmt.Printf("   Depth: %d layers\n\n", f.Depth)

	params := f.packParams()
	bestParams := make([]float32, len(params))
	copy(bestParams, params)
	bestLoss := f.loss(inputs, targets)

	sigma := float32(0.3)

	for epoch := 0; epoch < epochs; epoch++ {
		start := time.Now()
		improvements := 0

		for p := 0; p < population; p++ {
			// Mutate
			mutant := make([]float32, len(bestParams))
			noise := make([]float32, len(bestParams))
			for i := range mutant {
				noise[i] = randn() * sigma
				mutant[i] = bestParams[i] + noise[i]
			}

			f.unpackParams(mutant)
			mutLoss := f.loss(inputs, targets)

			if mutLoss < bestLoss {
				for i := range bestParams {
					bestParams[i] += 0.1 * noise[i]
				}
				bestLoss = mutLoss
				improvements++
			}
		}

		f.unpackParams(bestParams)
		if epoch%10 == 0 || epoch == epochs-1 {
			fmt.Printf("   Epoch %3d | Loss: %.6f | +%d | %v\n",
				epoch, bestLoss, improvements, time.Since(start).Round(time.Millisecond))
		}
		sigma *= 0.995
	}
}

func (f *FractalNet) packParams() []float32 {
	return []float32{f.A, f.B, f.C, f.D, f.E, f.F, f.G, f.H}
}

func (f *FractalNet) unpackParams(p []float32) {
	f.A, f.B, f.C, f.D, f.E, f.F, f.G, f.H = p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7]
}

func (f *FractalNet) loss(inputs, targets [][]float32) float32 {
	total := float32(0)
	for i, input := range inputs {
		out := f.Forward(input)
		for j := range out {
			d := out[j] - targets[i][j]
			total += d * d
		}
	}
	return total / float32(len(inputs))
}

// Helpers
var seed uint64 = 42
func randn() float32 {
	seed = seed*6364136223846793005 + 1442695040888963407
	return float32(seed>>33)/float32(1<<31) - 1.0
}
func sin(x float32) float32  { return float32(math.Sin(float64(x))) }
func cos(x float32) float32  { return float32(math.Cos(float64(x))) }
func relu(x float32) float32 { if x > 0 { return x }; return 0 }
func max(a, b int) int       { if a > b { return a }; return b }
